import os
import shutil
from PIL import Image, ImageDraw, ImageFont

def create_document(filename, title, content_dict):
    """Generates a pseudo-document as an image and saves it as PDF."""
    width, height = 800, 1000
    img = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(img)
    
    # Try to load a nice font, fallback to default
    try:
        font_title = ImageFont.truetype("Helvetica", 24)
        font_body = ImageFont.truetype("Helvetica", 16)
        font_header = ImageFont.truetype("Helvetica-Bold", 16)
    except IOError:
        font_title = ImageFont.load_default()
        font_body = ImageFont.load_default()
        font_header = ImageFont.load_default()

    # Draw border
    draw.rectangle([(20, 20), (width-20, height-20)], outline="black", width=2)
    
    # Draw Title
    draw.text((width/2 - 100, 50), title, fill="black", font=font_title)
    
    # Draw Document Content
    y_offset = 120
    for key, value in content_dict.items():
        draw.text((50, y_offset), f"{key}:", fill="black", font=font_header)
        # Handle multiline values
        if isinstance(value, str) and "\n" in value:
            lines = value.split("\n")
            for i, line in enumerate(lines):
                draw.text((250, y_offset + (i*25)), line, fill="black", font=font_body)
            y_offset += 25 * len(lines)
        else:
            draw.text((250, y_offset), str(value), fill="black", font=font_body)
        y_offset += 40

    # Draw footer
    draw.line([(50, height-100), (width-50, height-100)], fill="black", width=1)
    draw.text((50, height-80), "Generated by Nova Platform Testing Utility", fill="gray", font=font_body)
    
    # Save as PDF
    img.save(filename, "PDF", resolution=100.0)
    print(f"Generated {filename}")

def main():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    docs_dir = os.path.join(base_dir, "sample_documents")
    email1_dir = os.path.join(base_dir, "sample_emails", "email_1_clean")
    email2_dir = os.path.join(base_dir, "sample_emails", "email_2_messy")
    
    os.makedirs(docs_dir, exist_ok=True)
    os.makedirs(email1_dir, exist_ok=True)
    os.makedirs(email2_dir, exist_ok=True)

    # 1. Clean Bill of Lading
    bol_data = {
        "Shipper": "Shenzhen Electronics Co., Ltd.",
        "Consignee": "Meridian Global Imports Ltd.",
        "Port of Loading": "Shanghai",
        "Port of Discharge": "Rotterdam",
        "Container": "MSCU7234561",
        "Description": "Electronic Components - Integrated Circuit Modules",
        "HS Code": "85423100",
        "Gross Weight": "2450 KG",
        "Vessel": "MSC OSCAR",
        "B/L Number": "MSCUSHA2024001"
    }
    bol_path = os.path.join(docs_dir, "clean_bill_of_lading.pdf")
    create_document(bol_path, "BILL OF LADING", bol_data)

    # 2. Clean Commercial Invoice
    invoice_data = {
        "Invoice Number": "INV-20240315",
        "Date": "2024-03-15",
        "Seller": "Shenzhen Electronics Co., Ltd.",
        "Buyer": "Meridian Global Imports Ltd.",
        "Description": "Electronic Components - Integrated Circuit Modules",
        "HS Code": "85423100",
        "Quantity": "5000 units",
        "Unit Price": "USD 12.50",
        "Total": "USD 62,500.00",
        "Incoterms": "FOB Shanghai",
        "Payment": "T/T 30 days"
    }
    inv_path = os.path.join(docs_dir, "clean_commercial_invoice.pdf")
    create_document(inv_path, "COMMERCIAL INVOICE", invoice_data)

    # 3. Clean Packing List
    packing_data = {
        "Invoice Reference": "INV-20240315",
        "Consignee": "Meridian Global Imports Ltd.",
        "Packaging Details": "10 cartons, each 50cm x 40cm x 30cm",
        "Net Weight": "2200 KG",
        "Gross Weight": "2450 KG",
        "Container": "MSCU7234561"
    }
    pack_path = os.path.join(docs_dir, "clean_packing_list.pdf")
    create_document(pack_path, "PACKING LIST", packing_data)

    # 4. Messy Commercial Invoice
    messy_invoice_data = {
        "Invoice Number": "12345",  # Doesn't match expected pattern
        "Date": "2024-03-15",
        "Seller": "Shenzhen Electronics Co., Ltd.",
        "Buyer": "Merdian Global Import Ltd",  # Typo + missing 's'
        "Description": "sample goods",  # Banned keyword
        "HS Code": "9999",  # Invalid - too short
        "Quantity": "5000 units",
        "Unit Price": "USD 12.50",
        "Total": "USD 62,500.00",
        # Missing Incoterms field
        "Port of Discharge": "New York",  # Not in allowed list
        "Weight": "-50 KG",  # Invalid negative
        "Payment": "T/T 30 days"
    }
    messy_inv_path = os.path.join(docs_dir, "messy_commercial_invoice.pdf")
    create_document(messy_inv_path, "COMMERCIAL INVOICE", messy_invoice_data)

    # Copy to email directories
    shutil.copy2(bol_path, os.path.join(email1_dir, "bill_of_lading.pdf"))
    shutil.copy2(inv_path, os.path.join(email1_dir, "commercial_invoice.pdf"))
    shutil.copy2(pack_path, os.path.join(email1_dir, "packing_list.pdf"))
    print(f"Copied clean documents to {email1_dir}")

    shutil.copy2(messy_inv_path, os.path.join(email2_dir, "invoice_scan.pdf"))
    print(f"Copied messy document to {email2_dir}")

if __name__ == "__main__":
    main()
